/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as GippyAiRouteImport } from './routes/gippy-ai'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as B2bRouteImport } from './routes/b2b'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogIndexRouteImport } from './routes/catalog.index'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as CatalogCatalogIdRouteImport } from './routes/catalog.$catalogId'
import { Route as BrandBrandKeyRouteImport } from './routes/brand.$brandKey'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const GippyAiRoute = GippyAiRouteImport.update({
  id: '/gippy-ai',
  path: '/gippy-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const B2bRoute = B2bRouteImport.update({
  id: '/b2b',
  path: '/b2b',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductsRoute,
} as any)
const CatalogCatalogIdRoute = CatalogCatalogIdRouteImport.update({
  id: '/catalog/$catalogId',
  path: '/catalog/$catalogId',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandBrandKeyRoute = BrandBrandKeyRouteImport.update({
  id: '/$brandKey',
  path: '/$brandKey',
  getParentRoute: () => BrandRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/brand': typeof BrandRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gippy-ai': typeof GippyAiRoute
  '/products': typeof ProductsRouteWithChildren
  '/brand/$brandKey': typeof BrandBrandKeyRoute
  '/catalog/$catalogId': typeof CatalogCatalogIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/catalog/': typeof CatalogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/brand': typeof BrandRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gippy-ai': typeof GippyAiRoute
  '/products': typeof ProductsRouteWithChildren
  '/brand/$brandKey': typeof BrandBrandKeyRoute
  '/catalog/$catalogId': typeof CatalogCatalogIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/catalog': typeof CatalogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/b2b': typeof B2bRoute
  '/brand': typeof BrandRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/gippy-ai': typeof GippyAiRoute
  '/products': typeof ProductsRouteWithChildren
  '/brand/$brandKey': typeof BrandBrandKeyRoute
  '/catalog/$catalogId': typeof CatalogCatalogIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/catalog/': typeof CatalogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/b2b'
    | '/brand'
    | '/contact'
    | '/events'
    | '/gippy-ai'
    | '/products'
    | '/brand/$brandKey'
    | '/catalog/$catalogId'
    | '/products/$productId'
    | '/catalog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/b2b'
    | '/brand'
    | '/contact'
    | '/events'
    | '/gippy-ai'
    | '/products'
    | '/brand/$brandKey'
    | '/catalog/$catalogId'
    | '/products/$productId'
    | '/catalog'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/b2b'
    | '/brand'
    | '/contact'
    | '/events'
    | '/gippy-ai'
    | '/products'
    | '/brand/$brandKey'
    | '/catalog/$catalogId'
    | '/products/$productId'
    | '/catalog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  B2bRoute: typeof B2bRoute
  BrandRoute: typeof BrandRouteWithChildren
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GippyAiRoute: typeof GippyAiRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  CatalogCatalogIdRoute: typeof CatalogCatalogIdRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gippy-ai': {
      id: '/gippy-ai'
      path: '/gippy-ai'
      fullPath: '/gippy-ai'
      preLoaderRoute: typeof GippyAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/b2b': {
      id: '/b2b'
      path: '/b2b'
      fullPath: '/b2b'
      preLoaderRoute: typeof B2bRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/catalog/$catalogId': {
      id: '/catalog/$catalogId'
      path: '/catalog/$catalogId'
      fullPath: '/catalog/$catalogId'
      preLoaderRoute: typeof CatalogCatalogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/$brandKey': {
      id: '/brand/$brandKey'
      path: '/$brandKey'
      fullPath: '/brand/$brandKey'
      preLoaderRoute: typeof BrandBrandKeyRouteImport
      parentRoute: typeof BrandRoute
    }
  }
}

interface BrandRouteChildren {
  BrandBrandKeyRoute: typeof BrandBrandKeyRoute
}

const BrandRouteChildren: BrandRouteChildren = {
  BrandBrandKeyRoute: BrandBrandKeyRoute,
}

const BrandRouteWithChildren = BrandRoute._addFileChildren(BrandRouteChildren)

interface ProductsRouteChildren {
  ProductsProductIdRoute: typeof ProductsProductIdRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsProductIdRoute: ProductsProductIdRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  B2bRoute: B2bRoute,
  BrandRoute: BrandRouteWithChildren,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GippyAiRoute: GippyAiRoute,
  ProductsRoute: ProductsRouteWithChildren,
  CatalogCatalogIdRoute: CatalogCatalogIdRoute,
  CatalogIndexRoute: CatalogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
